title: Hyperbee Expressions
description: Documentation for Hyperbee Expressions — async, yield, loop, and compiler extensions for .NET expression trees.
remote_theme: pmarsceill/just-the-docs
baseurl: "/hyperbee.expressions/"
url: "https://stillpoint-software.github.io"

aux_links:
  "GitHub Repository":
    - "//github.com/Stillpoint-Software/hyperbee.expressions"

footer_content: |
  <div>
    <span>&copy; <span id="copyright-year"></span> <a href='https://www.stillpointsoftware.net/'>Stillpoint Software</a>.</span>
    <script>
      document.getElementById("copyright-year").textContent = new Date().getFullYear();
    </script>
  </div>

search_enabled: true

nav_external_links:
  - title: Stillpoint Software
    url: https://www.stillpointsoftware.net/
    opens_in_new_tab: true
